<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "campus_events_connector"
 *
 * Auto generated by Extension Builder 2018-06-21
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

/** @var string $_EXTKEY */
$EM_CONF[$_EXTKEY] = [
    'title' => 'CampusEvents Connector',
    'description' => '',
    'category' => 'be',
    'author' => 'Joshua Billert',
    'author_email' => 'joshua.billert@brain-appeal.com',
    'state' => 'beta',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 1,
    'version' => '0.5.2',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-7.6.99|8.7.0-8.7.99|>=9.3.0',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
    'autoload' => [
        'psr-4' => ['BrainAppeal\\CampusEventsConnector\\' => 'Classes'],
    ],
];
