services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  BrainAppeal\CampusEventsConnector\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/Domain/Model/*'
      - '../Classes/**/Exception.php'

  BrainAppeal\CampusEventsConnector\CeImport\ImportRunner:
    public: true
    #shared: true

  BrainAppeal\CampusEventsConnector\CeImport\DataCollection\CeApiConnector:
    public: true
    #shared: true

  BrainAppeal\CampusEventsConnector\Import\Configuration\ImportTableConfigurationProvider:
    shared: true
